name: default

kind: pipeline
type: docker

steps:
- name: python-project-test
  image: python
  commands:
    - pip install python-project/.
    - pytest python-project
  when:
    ref: 
    - refs/tags/v[0-9].[0-9]
