name: default

kind: pipeline
type: docker

steps:
- name: python-project-test
  image: python
  commands:
    - pip install python-project/.
    - pytest python-project
  settings:
    tags: ${DRONE_TAG##v}      
  when:
    event:
    - push
    - tag